// <auto-generated />
using System;
using CarRental.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarRental.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260414161404_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarRental.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactInformation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAAR");

                    b.Property<string>("DriverLicenseNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAAR");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAAR");

                    b.HasKey("Id");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("CarRental.Domain.Entities.FuleType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR");

                    b.HasKey("Id");

                    b.ToTable("FuleTypes", (string)null);
                });

            modelBuilder.Entity("CarRental.Domain.Entities.Maintenance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("NVARCHAR");

                    b.Property<DateTime>("MaintenanceDate")
                        .HasColumnType("date");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("Maintenances", (string)null);
                });

            modelBuilder.Entity("CarRental.Domain.Entities.RentalBooking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("DropoffLocation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR");

                    b.Property<byte>("InitialRentalDays")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("InitialTotalDueAmount")
                        .HasColumnType("smallmoney");

                    b.Property<string>("IntialCheckNotes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("PickupLocation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR");

                    b.Property<DateTime?>("RentalEndDate")
                        .HasColumnType("date");

                    b.Property<decimal>("RentalPricePerDay")
                        .HasColumnType("smallmoney");

                    b.Property<DateTime>("RentalStartDate")
                        .HasColumnType("date");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("VehicleId");

                    b.ToTable("RentalBookings", (string)null);
                });

            modelBuilder.Entity("CarRental.Domain.Entities.RentalTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ActualTotalDueAmount")
                        .HasColumnType("smallmoney");

                    b.Property<decimal>("PaidInitialTotalDueAmount")
                        .HasColumnType("smallmoney");

                    b.Property<string>("PaymentDetails")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR");

                    b.Property<int>("RentalBookingId")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalRefundedAmount")
                        .HasColumnType("smallmoney");

                    b.Property<decimal?>("TotalRemaining")
                        .HasColumnType("smallmoney");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("UpdatedTransactionDate")
                        .HasColumnType("datetime");

                    b.Property<int>("VehicleReturnId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RentalBookingId")
                        .IsUnique();

                    b.HasIndex("VehicleReturnId")
                        .IsUnique();

                    b.ToTable("RentalTransactions", (string)null);
                });

            modelBuilder.Entity("CarRental.Domain.Entities.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FuleTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR");

                    b.Property<int?>("Mileage")
                        .HasColumnType("INT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR");

                    b.Property<decimal>("RentalPricePerDay")
                        .HasColumnType("decimal");

                    b.Property<int>("VehicleCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("INT");

                    b.HasKey("Id");

                    b.HasIndex("FuleTypeId");

                    b.HasIndex("VehicleCategoryId");

                    b.ToTable("Vehicles", (string)null);
                });

            modelBuilder.Entity("CarRental.Domain.Entities.VehicleCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR");

                    b.HasKey("Id");

                    b.ToTable("VehicleCategories", (string)null);
                });

            modelBuilder.Entity("CarRental.Domain.Entities.VehicleReturn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte?>("ActualRentalDays")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("ActualReturnDate")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("ActualTotalDueAmount")
                        .HasMaxLength(500)
                        .HasColumnType("smallmoney");

                    b.Property<decimal?>("AdditionalCharges")
                        .HasMaxLength(500)
                        .HasColumnType("smallmoney");

                    b.Property<short?>("ConsumedMilaeage")
                        .HasColumnType("smallint");

                    b.Property<string>("FinalCheckNotes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar");

                    b.Property<short?>("Mileage")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("VehicleReturns", (string)null);
                });

            modelBuilder.Entity("CarRental.Domain.Entities.Maintenance", b =>
                {
                    b.HasOne("CarRental.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("Maintenances")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("CarRental.Domain.Entities.RentalBooking", b =>
                {
                    b.HasOne("CarRental.Domain.Entities.Customer", "Customer")
                        .WithMany("RentalBookings")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarRental.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("RentalBookings")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("CarRental.Domain.Entities.RentalTransaction", b =>
                {
                    b.HasOne("CarRental.Domain.Entities.RentalBooking", "RentalBooking")
                        .WithOne("Transaction")
                        .HasForeignKey("CarRental.Domain.Entities.RentalTransaction", "RentalBookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarRental.Domain.Entities.VehicleReturn", "VehicleReturn")
                        .WithOne("RentalTransaction")
                        .HasForeignKey("CarRental.Domain.Entities.RentalTransaction", "VehicleReturnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RentalBooking");

                    b.Navigation("VehicleReturn");
                });

            modelBuilder.Entity("CarRental.Domain.Entities.Vehicle", b =>
                {
                    b.HasOne("CarRental.Domain.Entities.FuleType", "FuleType")
                        .WithMany("Vehicles")
                        .HasForeignKey("FuleTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarRental.Domain.Entities.VehicleCategory", "VehicleCategory")
                        .WithMany("Vehicles")
                        .HasForeignKey("VehicleCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FuleType");

                    b.Navigation("VehicleCategory");
                });

            modelBuilder.Entity("CarRental.Domain.Entities.Customer", b =>
                {
                    b.Navigation("RentalBookings");
                });

            modelBuilder.Entity("CarRental.Domain.Entities.FuleType", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("CarRental.Domain.Entities.RentalBooking", b =>
                {
                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("CarRental.Domain.Entities.Vehicle", b =>
                {
                    b.Navigation("Maintenances");

                    b.Navigation("RentalBookings");
                });

            modelBuilder.Entity("CarRental.Domain.Entities.VehicleCategory", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("CarRental.Domain.Entities.VehicleReturn", b =>
                {
                    b.Navigation("RentalTransaction")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
